server:
  port: 8080
#数据连接
spring:
  datasource:
    # 数据库设置
    url: jdbc:mysql://localhost:3306/abc?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    # redis设置
  redis:
    host: localhost
    port: 6379
    password:
  #全文搜素配置
  elasticsearch:
    rest:
      uris: http://localhost:9200

#打印sql日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#平台配置
platform-config:
  system:
    enablePermission: true
    userInitPassword: 12345678
    tokenSecret: wqliu
    exportDataPageSize: 2











